language: ruby
rvm:
- 2.6.0
before_install:
- gem update --system
- gem install bundler
script:
- git config --global user.email "mlc880926@gmail.com"
- git config --global user.name "Ma Lucheng"
- git config --global push.default simple
- bundle install
- bundle exec asciidoctor-pdf-cjk-kai_gen_gothic-install
- bundle exec rake
- git remote add upstream "https://${GH_TOKEN}@github.com/teddy-ma/how-to-learn-emacs-chinese-edition.git"
- git fetch upstream
- git reset upstream/gh-pages
- cp build/how-to-learn-emacs-html/how-to-learn-emacs-html/index.html .
- cp build/how-to-learn-emacs-pdf/how-to-learn-emacs-pdf.pdf .
- rm -rf vendor
- git add -A .
- git commit -m "update from travis"
- git push -q upstream HEAD:gh-pages
env:
  global:
    secure: Pvu0mnLn9lXG7eOIhTd0KVbn//T/XWGaG4YQ7OPy3Je/XhhaVO6Ufm4ZMl7zQE2DokNfg5vOkDRy8jdsOksvtekjsEGIeoxMhYeJoyzMBb6+SWyQ1+IziCLWJKSO57fzem2h8U7Ps5J1NIcI4yOZpnV0pRtEOzKHDuhKF/Jo6Zg=
